=== GiuambEng/NOW/FE/BW/tim.now.gui_pps/Schemas/REST/MonTempiattrvThreshold.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/MonTempiattrvThreshold" xmlns:tns="http://www.example.org/MonTempiattrvThreshold" elementFormDefault="qualified">

    <element name="rootList">
    	<complexType>
    		<sequence maxOccurs="1" minOccurs="0">

    			<choice maxOccurs="1" minOccurs="0">
    			    			<element name="items" maxOccurs="unbounded"
    				minOccurs="0">
    				<complexType>
    					<sequence>
    						<element name="tipoContatore" type="string"
    							maxOccurs="1" minOccurs="0">
    						</element>
    						<element name="statoRichiestaNow"
    							type="string" maxOccurs="1" minOccurs="0">
    						</element>
    						<element name="nomeSoglia" type="string"
    							maxOccurs="1" minOccurs="0">
    						</element>
    						<element name="tipoLavz" type="string"
    							maxOccurs="1" minOccurs="0">
    						</element>
    						<element name="offerta" type="string"
    							maxOccurs="1" minOccurs="0">
    						</element>
    					</sequence>
    				</complexType>
    			</element>
    			<element name="Resultset" maxOccurs="unbounded" minOccurs="0">
    				<complexType>
    					<sequence>
    						<element name="offerta" type="string"
    							maxOccurs="1" minOccurs="0">
    						</element>
    						<element name="tiplgLavrz" type="string"
    							maxOccurs="1" minOccurs="0">
    						</element>
    					</sequence>
    				</complexType>
    			</element>
    			
    			
    			</choice>
    		</sequence>
    	</complexType></element>
</schema>

=== GiuambEng/NOW/FE/BW/tim.now.gui_pps/Schemas/MonTempiattrvThreshold.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:rootList xmlns:tns="http://www.example.org/MonTempiattrvThreshold" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/MonTempiattrvThreshold REST/MonTempiattrvThreshold.xsd ">
	<tns:items>
		<tns:tipoContatore>ORD_ACC_SLA</tns:tipoContatore>
		<tns:statoRichiestaNow>ACCODATO</tns:statoRichiestaNow>
	</tns:items>
		<tns:items>
		<tns:tipoContatore>ORD_ACC_NOSLA</tns:tipoContatore>
		<tns:statoRichiestaNow>ACCODATO</tns:statoRichiestaNow>
	</tns:items>
	<tns:items>
		<tns:tipoContatore>ORD_ACQ_SLA</tns:tipoContatore>
		<tns:statoRichiestaNow>ACQUISITO</tns:statoRichiestaNow>
	</tns:items>
	<tns:items>
		<tns:tipoContatore>ORD_ACQ_NOSLA</tns:tipoContatore>
		<tns:statoRichiestaNow>ACQUISITO</tns:statoRichiestaNow>
	</tns:items>
	<tns:items>
		<tns:tipoContatore>ORD_ANN_SLA</tns:tipoContatore>
		<tns:statoRichiestaNow>IN ANNULLAMENTO SUL DELIVERY</tns:statoRichiestaNow>
	</tns:items>
	<tns:items>
		<tns:tipoContatore>ORD_ANN_NOSLA</tns:tipoContatore>
		<tns:statoRichiestaNow>IN ANNULLAMENTO SUL DELIVERY</tns:statoRichiestaNow>
	</tns:items>
	<tns:items>
		<tns:tipoContatore>ORD_HD_SLA</tns:tipoContatore>
		<tns:statoRichiestaNow>LAVORAZIONEHD</tns:statoRichiestaNow>
	</tns:items>
		<tns:items>
		<tns:tipoContatore>ORD_HD_NOSLA</tns:tipoContatore>
		<tns:statoRichiestaNow>LAVORAZIONEHD</tns:statoRichiestaNow>
	</tns:items>
	<tns:items>	
		<tns:tipoContatore>ORD_IND_SLA</tns:tipoContatore>
		<tns:statoRichiestaNow>INDELIVERY</tns:statoRichiestaNow>
	</tns:items>
	<tns:items>	
		<tns:tipoContatore>ORD_IND_NOSLA</tns:tipoContatore>
		<tns:statoRichiestaNow>INDELIVERY</tns:statoRichiestaNow>
	</tns:items>
	<tns:items>
		<tns:tipoContatore>ORD_INVD_SLA</tns:tipoContatore>
		<tns:statoRichiestaNow>INVIATOADELIVERY</tns:statoRichiestaNow>
	</tns:items>
	<tns:items>
		<tns:tipoContatore>ORD_INVD_NOSLA</tns:tipoContatore>
		<tns:statoRichiestaNow>INVIATOADELIVERY</tns:statoRichiestaNow>
	</tns:items>
	<tns:items>
		<tns:tipoContatore>ORD_PERV_SLA</tns:tipoContatore>
		<tns:statoRichiestaNow>PERVENUTO</tns:statoRichiestaNow>
	</tns:items>
	<tns:items>
		<tns:tipoContatore>ORD_PERV_NOSLA</tns:tipoContatore>
		<tns:statoRichiestaNow>PERVENUTO</tns:statoRichiestaNow>
	</tns:items>
	<tns:items>
		<tns:tipoContatore>ORD_SOS_SLA</tns:tipoContatore>
		<tns:statoRichiestaNow>SOSPESO</tns:statoRichiestaNow>
	</tns:items>
	<tns:items>
		<tns:tipoContatore>ORD_SOS_NOSLA</tns:tipoContatore>
		<tns:statoRichiestaNow>SOSPESO</tns:statoRichiestaNow>
	</tns:items>
	<tns:items>
		<tns:tipoContatore>ORD_VIR_SLA</tns:tipoContatore>
		<tns:statoRichiestaNow>VERIFICHEINRETE</tns:statoRichiestaNow>
	</tns:items>
	<tns:items>
		<tns:tipoContatore>ORD_VIR_NOSLA</tns:tipoContatore>
		<tns:statoRichiestaNow>VERIFICHEINRETE</tns:statoRichiestaNow>
	</tns:items>
</tns:rootList>
